### ISSUE TITLE
Install it on Reaction with Docker

### ISSUE THREAD

**Issue by mateomorrison** [getoutfitted/reaction-zopim#16]
I'm using Docker, how to install this plugin? @spencern

**Comment by spencern** [comment]
Hi @mateomorrison 

This is the old version. Thanks for raising this issue, I need to update all of our plugins to work with the new `imports` structure.

This plugin will not work as of right now. I'll try to get this and other key plugins we've developed updated this week.

**Comment by spencern** [comment]
Hi @mateomorrison 
I've pushed a new update to both the development and master branches that should help you use this plugin with modern Reaction Commerce. Let me know if you have any additional issues.
